#include "CmdGenSchema.h"
#include "CLIUtils.h"
#include "Workspace.h"

#include <iostream>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <cctype>
namespace fs = std::filesystem;

namespace {

// Map SCHEMA_* id -> C# type name and `[MarshalAs]` modifier.
struct CSharpTypeMap { const char* csType; const char* marshalAs; };
CSharpTypeMap mapType(uint32_t tid) {
    switch (tid) {
        case 1:  return { "bool",   "UnmanagedType.U1"        };  // SCHEMA_BOOL
        case 2:  return { "byte",   "UnmanagedType.U1"        };  // SCHEMA_U8
        case 3:  return { "ushort", "UnmanagedType.U2"        };  // SCHEMA_U16
        case 4:  return { "uint",   "UnmanagedType.U4"        };  // SCHEMA_U32
        case 5:  return { "ulong",  "UnmanagedType.U8"        };  // SCHEMA_U64
        case 6:  return { "sbyte",  "UnmanagedType.I1"        };  // SCHEMA_I8
        case 7:  return { "short",  "UnmanagedType.I2"        };  // SCHEMA_I16
        case 8:  return { "int",    "UnmanagedType.I4"        };  // SCHEMA_I32
        case 9:  return { "long",   "UnmanagedType.I8"        };  // SCHEMA_I64
        case 10: return { "float",  "UnmanagedType.R4"        };  // SCHEMA_F32
        case 11: return { "double", "UnmanagedType.R8"        };  // SCHEMA_F64
        case 12: return { "IntPtr", "UnmanagedType.SysInt"    };  // SCHEMA_PTR
        case 13: return { "IntPtr", "UnmanagedType.SysInt"    };  // SCHEMA_HANDLE
        case 14: return { "IntPtr", "UnmanagedType.SysInt"    };  // SCHEMA_STRUCT nested handled separately
        default: return { "byte",   "UnmanagedType.U1"        };
    }
}

// Pack=4 default (matches C# StructLayout.Pack=4 for cross-platform x64 ABI).
int mapSize(uint32_t tid) {
    switch (tid) {
        case 1: case 2: case 6: case 12: case 13: return 1;
        case 3: case 7: return 2;
        case 4: case 8: case 10: return 4;
        case 5: case 9: case 11: return 8;
        default: return 1;
    }
}

std::string upperCamel(std::string s) {
    if (s.empty()) return s;
    s[0] = (char)std::toupper((unsigned char)s[0]);
    return s;
}

} // anonymous

int CmdGenSchema::execute(const Args& args, Workspace& ws) {
    std::string modName = args.pos(0);
    bool force = args.has("--force");
    if (modName.empty()) {
        std::cerr << "Usage: forge gen-schema <ModuleInstance> [--force]" << std::endl;
        return 1;
    }
    fs::path modPath = ws.resolveModule(modName);
    if (modPath.empty()) {
        std::cerr << "ModuleInstance not found: " << modName << std::endl;
        return 1;
    }
    fs::path modJson = modPath / "module.json";
    if (!fs::exists(modJson)) {
        std::cerr << "module.json missing: " << modJson << std::endl;
        return 1;
    }
    json mj;
    try {
        std::ifstream f(modJson);
        f >> mj;
    } catch (const std::exception& e) {
        std::cerr << "Failed to parse module.json: " << e.what() << std::endl;
        return 1;
    }
    if (!mj.contains("types") || !mj["types"].is_array() || mj["types"].empty()) {
        std::cerr << "No 'types' array in module.json (skipping)" << std::endl;
        return 0;
    }

    std::string ns = "Arche." + modName;
    fs::path outDir = modPath / "src" / "main" / "csharp" / ns / "Generated";
    fs::create_directories(outDir);
    fs::path outFile = outDir / "Schema.cs";
    if (fs::exists(outFile) && !force) {
        std::cout << cli::gray("  Schema.cs already exists, use --force to overwrite") << std::endl;
        return 0;
    }

    std::ostringstream out;
    out << "// Auto-generated by `forge gen-schema " << modName << "` on "
        << __DATE__ << " " << __TIME__ << "\n";
    out << "// Do not edit by hand. Source of truth: " << modJson.filename().string() << "\n";
    out << "using System;\nusing System.Runtime.InteropServices;\n\n";
    out << "namespace " << ns << " {\n";

    for (auto& t : mj["types"]) {
        std::string name = t.value("name", "");
        if (name.empty()) continue;
        int pack = t.value("pack", 4);
        out << "    /// <summary>Mirror of " << name
            << " in C++ SCHEMA registry. Pack=" << pack << ".</summary>\n";
        out << "    [StructLayout(LayoutKind.Sequential, Pack = " << pack << ", CharSet = CharSet.Unicode)]\n";
        out << "    public struct " << upperCamel(name) << " {\n";
        if (t.contains("fields") && t["fields"].is_array()) {
            uint32_t offset = 0;
            uint32_t alignMax = 1;
            for (auto& f : t["fields"]) {
                uint32_t tid = f.value("type", (uint32_t)0);
                std::string fname = f.value("name", std::string("field"));
                auto m = mapType(tid);
                uint32_t sz = (uint32_t)mapSize(tid);
                uint32_t align = (sz <= 1) ? 1u : (sz <= 2 ? 2u : (sz <= 4 ? 4u : 8u));
                if (align > alignMax) alignMax = align;
                // align offset
                uint32_t pad = (align - (offset % align)) % align;
                offset += pad;
                if (tid == 14) {
                    // nested struct: caller can override with "ref=<Type>"
                    std::string ref = f.value("ref", std::string());
                    if (!ref.empty()) {
                        out << "        [MarshalAs(UnmanagedType.Struct)] public " << ref << " " << fname << ";\n";
                    } else {
                        out << "        [MarshalAs(UnmanagedType.SysInt)] public IntPtr " << fname << ";\n";
                    }
                } else if (tid == 12 || tid == 13) {
                    out << "        [MarshalAs(" << m.marshalAs << ")] public " << m.csType << " " << fname << ";\n";
                } else {
                    out << "        [MarshalAs(" << m.marshalAs << ")] public " << m.csType << " " << fname << ";\n";
                }
                offset += sz;
            }
            // tail align to struct alignment
            uint32_t tail = (alignMax - (offset % alignMax)) % alignMax;
            (void)tail;
        }
        out << "    }\n\n";
    }
    out << "}\n";

    std::ofstream of(outFile);
    of << out.str();
    of.close();

    std::cout << cli::iconOk() << " " << cli::bold("gen-schema")
              << " " << cli::cyan(modName)
              << " -> " << cli::gray(outFile.string()) << std::endl;
    return 0;
}
